PYTHON = python3

.PHONY: all clean ols ridge gd help

.DEFAULT_GOAL := help



clean:
	rm -rf figs/*
	rm -rf figs/


help:
	@echo "  clean  - Remove generated figures"
	@echo "  help   - Show this help message"