[project]
name = "project2"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "matplotlib",
    "scikit-learn",
    "jupyter",
    "autograd>=1.8.0",
    "tensorflow>=2.20.0",
    "torch>=2.8.0",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
]
